name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run biome ci .

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run test:coverage

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup tools
        uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
