name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Setup tools
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run biome ci .

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Setup tools
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run formatter, linter and import sorting with Biome
        run: bun run test:coverage

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Setup tools
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
